[package]
name = "egor00f/uiterminal"

description = "Small library for creating working terminal in UI"

version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "GPL-v3.0"

repository = "https://github/"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

private = false

[dependencies]


[server-dependencies]


[dev-dependencies]
